steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  - name: "gcr.io/backpackybook/firebase"
    args: ["use", "default"]

  - name: "gcr.io/backpackybook/firebase"
    args: ["deploy"]
